// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkdihwqsicsgrvbcmtod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZGlod3FzaWNzZ3J2YmNtdG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzAyNDcsImV4cCI6MjA2OTcwNjI0N30.3bwfxYzEmIbCp60NorrmD_a315gYtnw-FkPisE3WVyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});